# Generated by Django 4.0 on 2021-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_image', models.ImageField(upload_to='asset/mybrand/')),
                ('subtitle', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
