# Generated by Django 4.0 on 2021-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_nav_nav1_nav_nav2_nav_nav3_nav_nav4_nav_nav5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='nav9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
