# Generated by Django 4.0 on 2021-12-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_nav_nav9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nav',
            old_name='nav1',
            new_name='nav',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav2',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav3',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav4',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav5',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav6',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav7',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav8',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav9',
        ),
    ]
