# Generated by Django 4.0.1 on 2022-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='asset/intro/pofile/'),
        ),
        migrations.AddField(
            model_name='intro',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
