# Generated by Django 4.0.1 on 2022-01-21 10:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='asset/intro/pofile/')),
            ],
        ),
    ]
